### ISSUE TITLE
No Example doc found

### ISSUE THREAD

**Issue by iamcrazyshank** [alamoWEB/react-native-web-mapview#1]
I am trying to use this library but couldnt find and example doc

**Comment by alamowebcompany** [comment]
Hi @iamcrazyshank 

We will update our `example` folder but you can check the [Usage](https://github.com/alamoWEB/react-native-web-mapview#usage) section in the meanwhile.

The library's documentation is based on [react-native-maps' documentation](https://github.com/react-native-maps/react-native-maps#component-api), supporting those features listed in our `Usage` section.

If you have any doubts, please don´t hesitate to ask
Thanks!
